-- 첨부파일 정보 테이블
DROP TABLE ATTACH;
CREATE TABLE ATTACH (
    ATTACH_NO       NUMBER NOT NULL,
    PATH            VARCHAR2(300 BYTE) NOT NULL,
    ORIGIN_NAME     VARCHAR2(300 BYTE) NOT NULL,
    FILESYSTEM_NAME VARCHAR2(50 BYTE) NOT NULL,
    DOWNLOAD_COUNT  NUMBER,
    HAS_THUMBNAIL   NUMBER,
    UPLOAD_NO       NUMBER
);

-- 게시글 정보 테이블
DROP TABLE UPLOAD;
CREATE TABLE UPLOAD(
    UPLOAD_NO       NUMBER NOT NULL,
    UPLOAD_TITLE    VARCHAR2(1000 BYTE) NOT NULL,
    UPLOAD_CONTENT  CLOB,
    CREATED_AT      TIMESTAMP,
    MODIFIED_AT     TIMESTAMP

);

-- 기본키
ALTER TABLE ATTACH
    ADD CONSTRAINT PK_ATTACH
        PRIMARY KEY(ATTACH_NO);
        
ALTER TABLE UPLOAD
    ADD CONSTRAINT PK_UPLOAD
        PRIMARY KEY(UPLOAD_NO);
        
-- 외래키
ALTER TABLE ATTACH
    ADD CONSTRAINT FK_ATTACH_UPLOAD
        FOREIGN KEY(UPLOAD_NO) REFERENCES UPLOAD(UPLOAD_NO)
            ON DELETE CASCADE;
            
-- 시퀀스
DROP SEQUENCE ATTACH_SEQ;
CREATE SEQUENCE ATTACH_SEQ NOCACHE;
DROP SEQUENCE UPLOAD_SEQ;
CREATE SEQUENCE UPLOAD_SEQ NOCACHE;